### ISSUE TITLE
Blog Archive not showing months

### ISSUE THREAD

**Issue by 5salaat** [akulakov/django#2]
I'm following you tutorial on the blog(Django 1.5 version) and I'm using Django 1.6.  For some reason, the Archive Months side bar is not showing the months.  It seems like the list for months and years is not being created, and therfore not shown.  in list.html I am using:
{% block sidebar %}
<ul class="style2">
<h3>Monthly Archive<h3/>
<li><article>
        
        {% for ym in view.months %}
           {% ifchanged ym.0 %} {{ ym.0 }} <br /> {% endifchanged %}
            <a href="{% url 'archive_month' ym.0 ym.1 %}">{{ ym.2 }}</a> <br /> 
           
        {% endfor %}

</article>
</li>
</ul>
{% endblock %}

and in views.py the code for creating the list of archive months is:

# Imports {{{

import time
from calendar import month_name

from travelblog.models import *
from travelblog.forms import *
from masudtravels.shared.utils import *

from masudtravels.mcbv.list import ListView
from masudtravels.mcbv.list_custom import DetailListCreateView

# }}}

allpost = Post
class PostView(DetailListCreateView):
    """Show post, associated comments and an 'add comment' form."""
    detail_model    = Post
    list_model      = Comment
    modelform_class = CommentForm
    related_name    = "comments"
    fk_attr         = "post"
    template_name   = "post.html"

class Main(ListView):
    list_model    = Post
    paginate_by   = 10
    template_name = "list.html"

  
    def months(self):
        """Make a list of months to show archive links."""
        if not Post.obj.count(): return list()

        # set up variables
        current_year, current_month = time.localtime()[:2]
        first       = Post.obj.order_by("created")[0]
        first_year  = first.created.year
        first_month = first.created.month
        months      = list()
	
        # loop over years and months
        for year in range(current_year, first_year-1, -1):
            start, end = 12, 0
            if year == current_year : start = current_month
            if year == first_year   : end = first_month - 1

            for month in range(start, end, -1):
                if Post.obj.filter(created__year=year, created__month=month):
                    months.append((year, month, month_name[month]))
        return months
			

	

class ArchiveMonth(Main):
    paginate_by = None
   

    def get_list_queryset(self):
        year, month = self.args
        return Post.obj.filter(created__year=year, created__month=month).order_by("created")

and in base.html i am using:

{% block sidebar %}{% endblock %}

Thank you in advance for your help!

**Comment by akulakov** [comment]
Could not reproduce - please try with new version, pushed today, which was updated to work with & tested on django 1.7 (including months list in blog).

**Comment by frankovo** [comment]
The
